### ISSUE TITLE
ISO download failed

### ISSUE THREAD

**Issue by ikstream** [BlackArch/blackarch-virtualization#6]
make build fails for vagrant
 
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://mirror.rackspace.com/archlinux/iso/2016.08.01/archlinux-2016.08.01-dual.iso
    virtualbox-iso: Error downloading: checksums didn't match expected: c0d5b2bd4d01741a770c4229f8b2939eecca8275dc9207cf629d0fa07787160b
==> virtualbox-iso: ISO download failed.
Build 'virtualbox-iso' errored: ISO download failed.

The rackspace mirror no longer provides the 01.08.2016 iso

**Comment by heichblatt** [comment]
Fixed by PR #4
